# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

#before_script:
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
# Be aware that this takes around 20 minutes per build
# so total build time will be 20*NBUILDS/NRUNNERS

# for kubernetes dockers....
#variables:
#  DOCKER_HOST: tcp://docker:2375/
#
variables:
  DOCKER_HOST: tcp://docker:2376/
  DOCKER_TLS_CERTDIR: "/certs"


build-docker-master-16:
  stage: build
  script: 
    - echo $CI_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" https://$CI_REGISTRY
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:16-${CI_COMMIT_REF_SLUG}" "16"
    - docker tag "${CI_REGISTRY_IMAGE}:16-${CI_COMMIT_REF_SLUG}" "${CI_REGISTRY_IMAGE}:16"
    - docker push "${CI_REGISTRY_IMAGE}:16-${CI_COMMIT_REF_SLUG}"
    - docker push "${CI_REGISTRY_IMAGE}:16"
  only:
    - master

build-docker-master-17:
  stage: build
  script: 
    - echo $CI_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" https://$CI_REGISTRY
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:17-${CI_COMMIT_REF_SLUG}" "17"
    - docker tag "${CI_REGISTRY_IMAGE}:17-${CI_COMMIT_REF_SLUG}" "${CI_REGISTRY_IMAGE}:17"
    - docker tag "${CI_REGISTRY_IMAGE}:17-${CI_COMMIT_REF_SLUG}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:17-${CI_COMMIT_REF_SLUG}"
    - docker push "${CI_REGISTRY_IMAGE}:17"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master

